version: '3.7'

services:
  database:
    image: postgres
    container_name: coverage
    restart: always
    ports:
      - 5432:5432
    cpus: 0.5
    mem_limit: '2g'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=coverageDb
    volumes:
      - pgdata:/data/postgres

  test-runner:
    build: .
    command: sh -c "yarn test && exit"
    depends_on:
      - database

  app:
    build: .
    container_name: pricingAPI
    restart: always
    ports:
      - 3001:3001
    volumes:
      - .:/usr/app
    links:
      - database
      - test-runner
    depends_on:
      - database
      - test-runner

volumes:
  pgdata:
    driver: local
