version: '3.7'

services:
    database:
        image: postgres
        container_name: coverage
        restart: always
        ports:
            - 5432:5432
        cpus: 0.5  # Limite de 0.5 vCPUs
        mem_limit: '2g'

        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=password
            - POSTGRES_DB=coverageDb
        volumes:
            - pgdata:/data/postgres

    app:
        build: .
        container_name: pricingAPI
        restart: always
        ports:
            - 3001:3001

        volumes:
            - .:/usr/app
        links:
            - database
        depends_on:
            - database

volumes:
    pgdata:
        driver: local